server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
  password:
  url: jdbc:postgresql://localhost:5432//hotel-manager-db
  username:
jpa:
  hibernate:
  ddl-auto: create-drop
  properties: